reg1dv450/config/routes.rb
Rails.application.routes.draw do
  
  namespace :api, defaults: {format: 'json'} do
    
    resources :shows,   only:[:index,:create, :show, :update, :destroy] 
    resources :artists, only:[:index,:create, :show, :update, :destroy] 
    resources :venues,  only:[:index,:create, :show, :update, :destroy] 
    
    resources :shows do
      resources :shows
    end
  end
  
  root 'users#index'
  
  get 'users'                => 'users#index'
  get 'users/new'            => 'users#new',       as: :new_user
  post 'users'               => 'users#create'

  
  get 'apikeys'              => 'apikeys#show',    as: :apikey
  get 'apikeys/new'          => 'apikeys#new_app', as: :new_api
  post 'apikeys/new'         =>  'apikeys#create', as: :create_api
  get 'apikeysadmin'         => 'apikeys#admin',   as: :apikeyadmin
  get 'apikeys/:id'          => 'apikeys#show_app',as: :showapp
  get 'apikeys/delete/:id'   => 'apikeys#destroy', as: :destroyapp
  
  post 'login'    => 'session#login', as: :login
  get  'logout'   => 'session#logout', as: :logout
  
  
end

reg1dv450/app/models/application.rb
class Application < ActiveRecord::Base
    
     validates   :name,                      presence: true,
                                             uniqueness: {case_sensitive: false}
     
      require 'securerandom'

     before_create :createKey
     
    belongs_to :user
    
    private
    def createKey
         self.key = SecureRandom.hex
    end
end

reg1dv450/app/models/artist.rb
class Artist < ActiveRecord::Base
    has_many :setlists
    has_many :shows, :through=> :setlists
    validates   :name,                      presence: true
end

reg1dv450/app/models/creator.rb
class Creator < ActiveRecord::Base
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates   :name,                      presence: true,
                                            length: { minimum: 3}
    validates   :email,                     presence: true,
                                            format: { with: VALID_EMAIL_REGEX, on: :create },
                                            uniqueness: {case_sensitive: false}
    has_secure_password
   
    has_many :shows
    has_many :venues, through: :shows
end

reg1dv450/app/models/setlist.rb
class Setlist < ActiveRecord::Base
    belongs_to :artist
    belongs_to :show
end

reg1dv450/app/models/show.rb
class Show < ActiveRecord::Base
    belongs_to :creator
    belongs_to :venue
    has_many :setlists
    has_many :artists, :through => :setlists
    validates :name,        presence: true
    validates :description, presence: true
end

reg1dv450/app/models/user.rb
class User < ActiveRecord::Base
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates   :name,                      presence: true,
                                            length: { minimum: 3}
    validates   :email,                     presence: true,
                                            format: { with: VALID_EMAIL_REGEX, on: :create },
                                            uniqueness: {case_sensitive: false}
    has_secure_password
    
    has_many :applications

end

reg1dv450/app/models/venue.rb
class Venue < ActiveRecord::Base
    has_many :shows
    has_many :creators, through: :shows
    
    geocoded_by :adress
    
    validates :longitude, numericality: true,  presence: true
    validates :latitude,  numericality: true,  presence: true
    validates :latitude,  presence: true
end

reg1dv450/app/controllers/apikeys_controller.rb
class ApikeysController < ApplicationController
    
    include SessionHelper
    
    before_action :require_login
    before_action :require_admin, only: [:admin]
    
    def show_app
        @app = Application.find_by_id(params[:id])
        if(@app == nil)
            redirect_to apikey_path
        end
    end
    
    def new_app
        @app = Application.new
    end
    
    
    def create
        
        @app = Application.new(app_params)
        if @app.save
            @current_user.applications << @app
            redirect_to apikey_path, notice: "Application saved"
        else
            render :action=>'new_app'
        end
    end
    
    def app_params
     params.require(:application).permit(:user_id,:name,:key)
    end
    
    def show
        @user = current_user
    end
    
    def destroy
        @app = Application.find_by_id(params[:id]).destroy

       redirect_to apikeyadmin_path, notice: "App deleted"

    end
    
    def admin
        @users = User.all
    end
    
    
   
    
end

reg1dv450/app/controllers/users_controller.rb
class UsersController < ApplicationController
   
    def index
        @users = User.all
    end
    
    
    def new
        @user = User.new
    end
    
    
    def create
        @user = User.new(user_params)
         # No admin page for handling users yet
        @user.admin = false
        if @user.save
            redirect_to root_path
        else
           render :action=>'new'
        end
    end
    
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

reg1dv450/app/helpers/api_helper.rb
module ApiHelper
end

reg1dv450/app/helpers/apikeys_helper.rb
module ApikeysHelper
end

reg1dv450/app/helpers/application_helper.rb
module ApplicationHelper
    
    
end

reg1dv450/app/helpers/applications_helper.rb
module ApplicationsHelper
end

reg1dv450/app/helpers/apps_helper.rb
module AppsHelper
end

reg1dv450/app/helpers/artist_helper.rb
module ArtistHelper
end

reg1dv450/app/helpers/artists_helper.rb
module ArtistsHelper
end

reg1dv450/app/helpers/session_helper.rb
module SessionHelper
    
    # Returns true if the user is logged in, false otherwise.
    def require_login
        unless logged_in?
          redirect_to root_path 
        end
    end
    
    # Returns the current logged-in user (if any).
    def current_user
        @current_user ||= User.find_by_id(session[:userid])  if session[:userid]
    end
    
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end
    
    # Returns true if the user is logged in as admin, false otherwise.
    def admin?
         #warning: ADMIN must have id 0, rake db:seed to get admin and sample user
        logged_in? &&  current_user.admin
    end
    #
    def require_admin
        unless admin?
          redirect_to apikey_path
        end
    end
  
end

reg1dv450/app/helpers/show_helper.rb
module ShowHelper
end

reg1dv450/app/helpers/shows_helper.rb
module ShowsHelper
end

reg1dv450/app/helpers/user_api_helper.rb
module UserApiHelper
end

reg1dv450/app/helpers/users_helper.rb
module UsersHelper
end

reg1dv450/app/helpers/venues_helper.rb
module VenuesHelper
end

reg1dv450/app/views/apikeys/admin.html.erb
<div class="container">
<%  if flash[:notice] %>
    <div class="bg-warning text-warning">
       <p class="bg-info" <%= flash[:notice] %></p>
    </div>
<% end %>
<h2>Authorized API:s</h2>
<dl class="dl-vertical">
<% @users.each do |user| %>
  <dt><h4><%= user.name %></h4>
  
        <ul class="list-unstyled">
        <% user.applications.each do |app|%>
        <li> <%= link_to(app.name, showapp_path(app)) %> <%= link_to("Revoke", destroyapp_path(app),class:"btn btn-default") %></li>
        <% end %>
        </ul>
  </dt>
<% end %>
</dl>

<p><%= link_to("Log  Out", logout_path,class:"btn-primary btn-lg") %></p>

reg1dv450/app/views/apikeys/new_app.html.erb
<div class="container">
<% if @app.errors.any? %>
    <div id="error_message">
        <h2>There were some errors in the form</h2>
        <ul>
            <% @app.errors.full_messages.each do |msg| %>
            <li> <%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<p>
<h1>Register new API key</h1>
<fieldset>
<%= form_for @app,url: {action: "create"}, class:"form-inline" do |f| %>
<div class="form-group">
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
</div>
<div class="form-group">
<p><%= f.submit "Create app", class:"btn-primary btn-lg" %></p>
</div>
<% end %>
</fieldset>
</div>

reg1dv450/app/views/apikeys/show.html.erb
<div class="container">
<%  if flash[:notice] %>
    <div class="bg-warning text-warning">
       <p class="bg-info" <%= flash[:notice] %></p>
    </div>
<% end %>

<h1> Your API:s</h1>

<dl class="dl-vertical">
    <%@user.applications.each do |app| %>
    <dt>
    <p><%= link_to(app.name, showapp_path(app)) %> <%= link_to("Delete", destroyapp_path(app),class:"btn btn-default") %></p>
    </dt>
    <% end %>
</dl>


<p><%= link_to("Create new", new_api_path, class:"btn btn-default") %></p>
<br>
<p><%= link_to("Log  Out", logout_path,class:"btn-primary btn-lg") %></p>

reg1dv450/app/views/apikeys/show_app.html.erb
<div class="container">
<%  if flash[:notice] %>
    <div class="bg-warning text-warning">
       <p class="bg-info" <%= flash[:notice] %></p>
    </div>
<% end %>

<h1><%= @app.name %></h1>

<dl class="dl-vertical">
<dt>
<p>Key: <%= @app.key %> </p>
</dt>
<dl class="dl-vertical">
<p><%= link_to("Delete", destroyapp_path(@app),class:"btn btn-default") %></p>

<p><%= link_to("Back", apikeyadmin_path,class:"btn btn-default") %></p>